--------------------------------------------------------
--  파일이 생성됨 - 금요일-8월-28-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_COLLECTION
--------------------------------------------------------

   CREATE SEQUENCE  "ENDITPCWK"."SEQ_COLLECTION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 249 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONTENT
--------------------------------------------------------

   CREATE SEQUENCE  "ENDITPCWK"."SEQ_CONTENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 251 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONTENT_CREDIT
--------------------------------------------------------

   CREATE SEQUENCE  "ENDITPCWK"."SEQ_CONTENT_CREDIT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2743 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONTENT_IMAGE
--------------------------------------------------------

   CREATE SEQUENCE  "ENDITPCWK"."SEQ_CONTENT_IMAGE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4814 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_GENRE
--------------------------------------------------------

   CREATE SEQUENCE  "ENDITPCWK"."SEQ_GENRE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MEMBER
--------------------------------------------------------

   CREATE SEQUENCE  "ENDITPCWK"."SEQ_MEMBER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 346 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MEMBER_SOCIAL_ACCOUNT
--------------------------------------------------------

   CREATE SEQUENCE  "ENDITPCWK"."SEQ_MEMBER_SOCIAL_ACCOUNT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NOTICE
--------------------------------------------------------

   CREATE SEQUENCE  "ENDITPCWK"."SEQ_NOTICE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 184 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PERSON
--------------------------------------------------------

   CREATE SEQUENCE  "ENDITPCWK"."SEQ_PERSON"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1968 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REPORT
--------------------------------------------------------

   CREATE SEQUENCE  "ENDITPCWK"."SEQ_REPORT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 192 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER_COMMENT
--------------------------------------------------------

   CREATE SEQUENCE  "ENDITPCWK"."SEQ_USER_COMMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 911 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table COLLECTION
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."COLLECTION" 
   (	"COLLECTION_ID" NUMBER, 
	"MEMBER_ID" NUMBER, 
	"TITLE" NVARCHAR2(100), 
	"DESCRIPTION" NVARCHAR2(1000), 
	"IS_PUBLIC" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"UPDATED_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION"."COLLECTION_ID" IS '컬렉션번호 (PK)';
   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION"."MEMBER_ID" IS '작성회원번호 (FK)';
   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION"."TITLE" IS '컬렉션 제목';
   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION"."DESCRIPTION" IS '컬렉션 설명';
   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION"."IS_PUBLIC" IS '공개 여부 (Y/N)';
   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION"."CREATED_DT" IS '생성 일시';
   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION"."UPDATED_DT" IS '수정 일시';
   COMMENT ON TABLE "ENDITPCWK"."COLLECTION"  IS '회원이 만든 콘텐츠 컬렉션의 제목·설명·공개 상태 관리';
--------------------------------------------------------
--  DDL for Table COLLECTION_ITEM
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."COLLECTION_ITEM" 
   (	"COLLECTION_ID" NUMBER, 
	"CONTENT_ID" NUMBER, 
	"ADDED_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION_ITEM"."COLLECTION_ID" IS '컬렉션번호 (복합 PK, FK)';
   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION_ITEM"."CONTENT_ID" IS '콘텐츠번호 (복합 PK, FK)';
   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION_ITEM"."ADDED_DT" IS '추가 일시';
   COMMENT ON TABLE "ENDITPCWK"."COLLECTION_ITEM"  IS '컬렉션에 포함된 콘텐츠와 추가 일시 관리';
--------------------------------------------------------
--  DDL for Table COLLECTION_LIKE
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."COLLECTION_LIKE" 
   (	"MEMBER_ID" NUMBER, 
	"COLLECTION_ID" NUMBER, 
	"CREATED_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION_LIKE"."MEMBER_ID" IS '회원번호 (복합 PK, FK)';
   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION_LIKE"."COLLECTION_ID" IS '컬렉션번호 (복합 PK, FK)';
   COMMENT ON COLUMN "ENDITPCWK"."COLLECTION_LIKE"."CREATED_DT" IS '좋아요 일시';
   COMMENT ON TABLE "ENDITPCWK"."COLLECTION_LIKE"  IS '회원이 좋아요를 누른 컬렉션 기록 관리';
--------------------------------------------------------
--  DDL for Table COMMENT_LIKE
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."COMMENT_LIKE" 
   (	"MEMBER_ID" NUMBER, 
	"COMMENT_ID" NUMBER, 
	"CREATED_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."COMMENT_LIKE"."MEMBER_ID" IS '회원번호 (복합 PK, FK)';
   COMMENT ON COLUMN "ENDITPCWK"."COMMENT_LIKE"."COMMENT_ID" IS '코멘트번호 (복합 PK, FK)';
   COMMENT ON COLUMN "ENDITPCWK"."COMMENT_LIKE"."CREATED_DT" IS '좋아요 일시';
   COMMENT ON TABLE "ENDITPCWK"."COMMENT_LIKE"  IS '회원이 좋아요를 누른 코멘트 기록 관리';
--------------------------------------------------------
--  DDL for Table COMMON_CODE
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."COMMON_CODE" 
   (	"CODE" VARCHAR2(30 BYTE), 
	"GROUP_CODE" VARCHAR2(30 BYTE), 
	"CODE_NAME" NVARCHAR2(100), 
	"SORT_ORDER" NUMBER(3,0) DEFAULT 0, 
	"CREATED_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."COMMON_CODE"."CODE" IS '코드 값';
   COMMENT ON COLUMN "ENDITPCWK"."COMMON_CODE"."GROUP_CODE" IS '코드 그룹';
   COMMENT ON COLUMN "ENDITPCWK"."COMMON_CODE"."CODE_NAME" IS '한글명';
   COMMENT ON COLUMN "ENDITPCWK"."COMMON_CODE"."SORT_ORDER" IS '정렬 순서';
   COMMENT ON COLUMN "ENDITPCWK"."COMMON_CODE"."CREATED_DT" IS '등록 일시';
   COMMENT ON TABLE "ENDITPCWK"."COMMON_CODE"  IS '공통 코드 상세';
--------------------------------------------------------
--  DDL for Table COMMON_CODE_GROUP
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."COMMON_CODE_GROUP" 
   (	"GROUP_CODE" VARCHAR2(30 BYTE), 
	"GROUP_NAME" NVARCHAR2(100), 
	"DESCRIPTION" NVARCHAR2(500), 
	"CREATED_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."COMMON_CODE_GROUP"."GROUP_CODE" IS '코드 그룹';
   COMMENT ON COLUMN "ENDITPCWK"."COMMON_CODE_GROUP"."GROUP_NAME" IS '그룹명';
   COMMENT ON COLUMN "ENDITPCWK"."COMMON_CODE_GROUP"."DESCRIPTION" IS '그룹 설명';
   COMMENT ON COLUMN "ENDITPCWK"."COMMON_CODE_GROUP"."CREATED_DT" IS '등록 일시';
   COMMENT ON TABLE "ENDITPCWK"."COMMON_CODE_GROUP"  IS '공통 코드 그룹';
--------------------------------------------------------
--  DDL for Table CONTENT
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."CONTENT" 
   (	"CONTENT_ID" NUMBER, 
	"EXTERNAL_ID" VARCHAR2(50 BYTE), 
	"TITLE_KO" NVARCHAR2(200), 
	"TITLE_ORG" NVARCHAR2(200), 
	"OVERVIEW" CLOB, 
	"RELEASE_YEAR" DATE, 
	"RUNTIME_MIN" NUMBER(4,0), 
	"COUNTRY" NVARCHAR2(100), 
	"POSTER_URL" VARCHAR2(1000 BYTE), 
	"BACKDROP_URL" VARCHAR2(1000 BYTE), 
	"CREATED_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" 
 LOB ("OVERVIEW") STORE AS SECUREFILE (
  TABLESPACE "ENDIT_WEB_TS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "ENDITPCWK"."CONTENT"."CONTENT_ID" IS '영화번호 (PK)';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT"."EXTERNAL_ID" IS '외부 콘텐츠 식별값';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT"."TITLE_KO" IS '영화 국문 제목';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT"."TITLE_ORG" IS '영화 원문 제목';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT"."OVERVIEW" IS '줄거리';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT"."RELEASE_YEAR" IS '개봉년도';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT"."RUNTIME_MIN" IS '상영시간(분)';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT"."COUNTRY" IS '대표 제작국가';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT"."POSTER_URL" IS '포스터 URL';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT"."BACKDROP_URL" IS '배경 이미지 URL';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT"."CREATED_DT" IS '등록 일시';
   COMMENT ON TABLE "ENDITPCWK"."CONTENT"  IS '영화 콘텐츠 기본 정보, 외부 데이터 식별값 및 이미지 URL 관리';
--------------------------------------------------------
--  DDL for Table CONTENT_CREDIT
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."CONTENT_CREDIT" 
   (	"CREDIT_ID" NUMBER, 
	"CONTENT_ID" NUMBER, 
	"PERSON_ID" NUMBER, 
	"ROLE" VARCHAR2(20 BYTE), 
	"CHARACTER" NVARCHAR2(200), 
	"DISPLAY_ORDER" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_CREDIT"."CREDIT_ID" IS '참여정보번호 (PK)';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_CREDIT"."CONTENT_ID" IS '콘텐츠번호 (FK)';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_CREDIT"."PERSON_ID" IS '인물번호 (FK)';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_CREDIT"."ROLE" IS '참여 역할 코드 (ACTOR, DIRECTOR, WRITER, PRODUCER)';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_CREDIT"."CHARACTER" IS '배역명';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_CREDIT"."DISPLAY_ORDER" IS '표시 순서';
   COMMENT ON TABLE "ENDITPCWK"."CONTENT_CREDIT"  IS '콘텐츠에 참여한 배우·감독·작가·제작자와 역할 정보 관리';
--------------------------------------------------------
--  DDL for Table CONTENT_GENRE
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."CONTENT_GENRE" 
   (	"CONTENT_ID" NUMBER, 
	"GENRE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_GENRE"."CONTENT_ID" IS '영화 번호 (복합 PK, FK)';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_GENRE"."GENRE_ID" IS '장르 번호 (복합 PK, FK)';
   COMMENT ON TABLE "ENDITPCWK"."CONTENT_GENRE"  IS '콘텐츠와 장르의 다대다 관계 연결';
--------------------------------------------------------
--  DDL for Table CONTENT_IMAGE
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."CONTENT_IMAGE" 
   (	"IMAGE_ID" NUMBER, 
	"CONTENT_ID" NUMBER, 
	"IMAGE_URL" VARCHAR2(1000 BYTE), 
	"CREATED_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_IMAGE"."IMAGE_ID" IS '이미지 번호 (PK)';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_IMAGE"."CONTENT_ID" IS '콘텐츠 번호 (FK)';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_IMAGE"."IMAGE_URL" IS '이미지 URL';
   COMMENT ON COLUMN "ENDITPCWK"."CONTENT_IMAGE"."CREATED_DT" IS '등록 일시';
   COMMENT ON TABLE "ENDITPCWK"."CONTENT_IMAGE"  IS '영화별 스틸컷, 포스터, 배경 이미지 등 다중 이미지 URL 관리';
--------------------------------------------------------
--  DDL for Table GENRE
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."GENRE" 
   (	"GENRE_ID" NUMBER, 
	"EXTERNAL_GENRE_ID" VARCHAR2(50 BYTE), 
	"NAME" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."GENRE"."GENRE_ID" IS '장르번호 (PK)';
   COMMENT ON COLUMN "ENDITPCWK"."GENRE"."EXTERNAL_GENRE_ID" IS '외부 장르 식별값';
   COMMENT ON COLUMN "ENDITPCWK"."GENRE"."NAME" IS '장르명';
   COMMENT ON TABLE "ENDITPCWK"."GENRE"  IS '콘텐츠 장르 기준 정보 관리';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."MEMBER" 
   (	"MEMBER_ID" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"NICKNAME" NVARCHAR2(30), 
	"INTRODUCTION" NVARCHAR2(300), 
	"PROFILE_IMG_URL" VARCHAR2(1000 BYTE), 
	"ROLE" VARCHAR2(20 BYTE) DEFAULT 'USER', 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"UPDATED_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."MEMBER"."MEMBER_ID" IS '회원번호 (PK)';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER"."PASSWORD" IS '비밀번호 (소셜 전용은 NULL)';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER"."NICKNAME" IS '닉네임';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER"."INTRODUCTION" IS '소개';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER"."PROFILE_IMG_URL" IS '프로필 이미지 URL';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER"."ROLE" IS '회원 권한 (USER, ADMIN)';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER"."CREATED_DT" IS '가입 일시';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER"."UPDATED_DT" IS '수정 일시';
   COMMENT ON TABLE "ENDITPCWK"."MEMBER"  IS '이메일·소셜 회원의 계정, 공개 프로필, 권한 관리';
--------------------------------------------------------
--  DDL for Table MEMBER_CONTENT
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."MEMBER_CONTENT" 
   (	"MEMBER_ID" NUMBER, 
	"CONTENT_ID" NUMBER, 
	"RATING_SCORE" NUMBER(1,0), 
	"WATCHLIST" CHAR(1 BYTE) DEFAULT 'N', 
	"RATED_DT" DATE, 
	"WATCHLIST_DT" DATE, 
	"UPDATED_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_CONTENT"."MEMBER_ID" IS '회원번호 (복합 PK, FK)';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_CONTENT"."CONTENT_ID" IS '콘텐츠번호 (복합 PK, FK)';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_CONTENT"."RATING_SCORE" IS '별점 (1~5, 미평가 시 NULL)';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_CONTENT"."WATCHLIST" IS '보고싶어요 여부 (Y/N)';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_CONTENT"."RATED_DT" IS '평가 일시';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_CONTENT"."WATCHLIST_DT" IS '보고싶어요 등록 일시';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_CONTENT"."UPDATED_DT" IS '최종 변경 일시';
   COMMENT ON TABLE "ENDITPCWK"."MEMBER_CONTENT"  IS '회원별 콘텐츠 별점과 보고싶어요 상태를 한 행으로 관리';
--------------------------------------------------------
--  DDL for Table MEMBER_SOCIAL_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" 
   (	"MEMBER_SOCIAL_ACCOUNT_ID" NUMBER, 
	"MEMBER_ID" NUMBER, 
	"PROVIDER_CODE" VARCHAR2(20 BYTE), 
	"PROVIDER_USER_ID" VARCHAR2(255 BYTE), 
	"PROVIDER_EMAIL" VARCHAR2(255 BYTE), 
	"CONNECTED_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT"."MEMBER_SOCIAL_ACCOUNT_ID" IS '회원 소셜 계정 번호 (PK)';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT"."MEMBER_ID" IS '회원번호 (FK)';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT"."PROVIDER_CODE" IS '소셜 제공자 (GOOGLE, KAKAO, NAVER)';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT"."PROVIDER_USER_ID" IS '제공자 회원식별값';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT"."PROVIDER_EMAIL" IS '제공자 이메일';
   COMMENT ON COLUMN "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT"."CONNECTED_DT" IS '연동 일시';
   COMMENT ON TABLE "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT"  IS '회원과 소셜 로그인(Google, Kakao, Naver) 계정 연결 정보 관리';
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."NOTICE" 
   (	"NOTICE_ID" NUMBER, 
	"TITLE" NVARCHAR2(200), 
	"CONTENT" CLOB, 
	"IMPORTANT" CHAR(1 BYTE) DEFAULT 'N', 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'DRAFT', 
	"VIEW_COUNT" NUMBER(10,0) DEFAULT 0, 
	"CREATED_ID" NUMBER, 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"UPDATED_ID" NUMBER, 
	"UPDATED_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "ENDIT_WEB_TS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "ENDITPCWK"."NOTICE"."NOTICE_ID" IS '공지번호 (PK)';
   COMMENT ON COLUMN "ENDITPCWK"."NOTICE"."TITLE" IS '제목';
   COMMENT ON COLUMN "ENDITPCWK"."NOTICE"."CONTENT" IS '본문';
   COMMENT ON COLUMN "ENDITPCWK"."NOTICE"."IMPORTANT" IS '중요 공지 여부 (Y/N)';
   COMMENT ON COLUMN "ENDITPCWK"."NOTICE"."STATUS" IS '게시 상태 (DRAFT, PUBLISHED, HIDDEN)';
   COMMENT ON COLUMN "ENDITPCWK"."NOTICE"."VIEW_COUNT" IS '조회수';
   COMMENT ON COLUMN "ENDITPCWK"."NOTICE"."CREATED_ID" IS '등록자 (FK)';
   COMMENT ON COLUMN "ENDITPCWK"."NOTICE"."CREATED_DT" IS '등록 일시';
   COMMENT ON COLUMN "ENDITPCWK"."NOTICE"."UPDATED_ID" IS '수정자 (FK)';
   COMMENT ON COLUMN "ENDITPCWK"."NOTICE"."UPDATED_DT" IS '수정 일시';
   COMMENT ON TABLE "ENDITPCWK"."NOTICE"  IS '관리자가 등록하는 공지사항의 게시 상태와 중요 표시 관리';
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."PERSON" 
   (	"PERSON_ID" NUMBER, 
	"EXTERNAL_ID" VARCHAR2(50 BYTE), 
	"NAME_KO" NVARCHAR2(100), 
	"NAME_ORG" NVARCHAR2(100), 
	"PROFILE_IMAGE_URL" VARCHAR2(1000 BYTE), 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"UPDATED_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."PERSON"."PERSON_ID" IS '인물번호 (PK)';
   COMMENT ON COLUMN "ENDITPCWK"."PERSON"."EXTERNAL_ID" IS '외부 인물 식별값';
   COMMENT ON COLUMN "ENDITPCWK"."PERSON"."NAME_KO" IS '인물명_국문';
   COMMENT ON COLUMN "ENDITPCWK"."PERSON"."NAME_ORG" IS '인물명_원문';
   COMMENT ON COLUMN "ENDITPCWK"."PERSON"."PROFILE_IMAGE_URL" IS '프로필 이미지 URL';
   COMMENT ON COLUMN "ENDITPCWK"."PERSON"."CREATED_DT" IS '등록 일시';
   COMMENT ON COLUMN "ENDITPCWK"."PERSON"."UPDATED_DT" IS '수정 일시';
   COMMENT ON TABLE "ENDITPCWK"."PERSON"  IS '배우·감독 등 콘텐츠 참여 인물의 기본 정보 관리';
--------------------------------------------------------
--  DDL for Table PERSON_LIKE
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."PERSON_LIKE" 
   (	"MEMBER_ID" NUMBER, 
	"PERSON_ID" NUMBER, 
	"CREATED_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."PERSON_LIKE"."MEMBER_ID" IS '회원번호 (복합 PK, FK)';
   COMMENT ON COLUMN "ENDITPCWK"."PERSON_LIKE"."PERSON_ID" IS '인물번호 (복합 PK, FK)';
   COMMENT ON COLUMN "ENDITPCWK"."PERSON_LIKE"."CREATED_DT" IS '좋아요 일시';
   COMMENT ON TABLE "ENDITPCWK"."PERSON_LIKE"  IS '회원이 좋아요를 누른 배우·감독 등 인물 기록 관리';
--------------------------------------------------------
--  DDL for Table REPORT_COMMENT
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."REPORT_COMMENT" 
   (	"REPORT_ID" NUMBER, 
	"REPORT_MEMBER_ID" NUMBER, 
	"COMMENT_ID" NUMBER, 
	"REASON" VARCHAR2(30 BYTE), 
	"DETAIL" NVARCHAR2(1000), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'RECEIVED', 
	"PROCESSED_BY_MEMBER_ID" NUMBER, 
	"PROCESS_NOTE" NVARCHAR2(1000), 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"PROCESSED_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;

   COMMENT ON COLUMN "ENDITPCWK"."REPORT_COMMENT"."REPORT_ID" IS '신고번호 (PK)';
   COMMENT ON COLUMN "ENDITPCWK"."REPORT_COMMENT"."REPORT_MEMBER_ID" IS '신고회원번호 (FK)';
   COMMENT ON COLUMN "ENDITPCWK"."REPORT_COMMENT"."COMMENT_ID" IS '신고 코멘트번호 (FK)';
   COMMENT ON COLUMN "ENDITPCWK"."REPORT_COMMENT"."REASON" IS '신고 사유 (SPOILER, INAPPROPRIATE, SPAM, OTHER)';
   COMMENT ON COLUMN "ENDITPCWK"."REPORT_COMMENT"."DETAIL" IS '상세 내용 (OTHER 선택 시 필수)';
   COMMENT ON COLUMN "ENDITPCWK"."REPORT_COMMENT"."STATUS" IS '처리 상태 (RECEIVED, PROCESSING, ACCEPTED, REJECTED)';
   COMMENT ON COLUMN "ENDITPCWK"."REPORT_COMMENT"."PROCESSED_BY_MEMBER_ID" IS '처리 관리자번호 (FK)';
   COMMENT ON COLUMN "ENDITPCWK"."REPORT_COMMENT"."PROCESS_NOTE" IS '처리 내용';
   COMMENT ON COLUMN "ENDITPCWK"."REPORT_COMMENT"."CREATED_DT" IS '신고 일시';
   COMMENT ON COLUMN "ENDITPCWK"."REPORT_COMMENT"."PROCESSED_DT" IS '처리 일시';
   COMMENT ON TABLE "ENDITPCWK"."REPORT_COMMENT"  IS '코멘트 신고 접수와 관리자 처리 결과 관리';
--------------------------------------------------------
--  DDL for Table USER_COMMENT
--------------------------------------------------------

  CREATE TABLE "ENDITPCWK"."USER_COMMENT" 
   (	"COMMENT_ID" NUMBER, 
	"MEMBER_ID" NUMBER, 
	"CONTENT_ID" NUMBER, 
	"COLLECTION_ID" NUMBER, 
	"COMMENT_DETAIL" CLOB, 
	"SPOILER" CHAR(1 BYTE) DEFAULT 'N', 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"UPDATED_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" 
 LOB ("COMMENT_DETAIL") STORE AS SECUREFILE (
  TABLESPACE "ENDIT_WEB_TS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "ENDITPCWK"."USER_COMMENT"."COMMENT_ID" IS '코멘트번호 (PK)';
   COMMENT ON COLUMN "ENDITPCWK"."USER_COMMENT"."MEMBER_ID" IS '작성 회원번호 (FK)';
   COMMENT ON COLUMN "ENDITPCWK"."USER_COMMENT"."CONTENT_ID" IS '콘텐츠 번호 (FK, NULL 허용)';
   COMMENT ON COLUMN "ENDITPCWK"."USER_COMMENT"."COLLECTION_ID" IS '컬렉션 번호 (FK, NULL 허용)';
   COMMENT ON COLUMN "ENDITPCWK"."USER_COMMENT"."COMMENT_DETAIL" IS '코멘트 내용';
   COMMENT ON COLUMN "ENDITPCWK"."USER_COMMENT"."SPOILER" IS '스포일러 여부 (Y/N)';
   COMMENT ON COLUMN "ENDITPCWK"."USER_COMMENT"."CREATED_DT" IS '작성 일시';
   COMMENT ON COLUMN "ENDITPCWK"."USER_COMMENT"."UPDATED_DT" IS '수정 일시';
   COMMENT ON TABLE "ENDITPCWK"."USER_COMMENT"  IS '회원이 콘텐츠 또는 컬렉션에 작성한 코멘트와 스포일러 상태 관리';
--------------------------------------------------------
--  DDL for Index PK_PERSON
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_PERSON" ON "ENDITPCWK"."PERSON" ("PERSON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index UK_PERSON_EXTERNAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."UK_PERSON_EXTERNAL" ON "ENDITPCWK"."PERSON" ("EXTERNAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER_SOCIAL_ACCOUNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_MEMBER_SOCIAL_ACCOUNT" ON "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" ("MEMBER_SOCIAL_ACCOUNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index UK_MEMBER_SOCIAL_PROVIDER_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."UK_MEMBER_SOCIAL_PROVIDER_USER" ON "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" ("PROVIDER_CODE", "PROVIDER_USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index UK_MEMBER_SOCIAL_MEMBER_PROVIDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."UK_MEMBER_SOCIAL_MEMBER_PROVIDER" ON "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" ("MEMBER_ID", "PROVIDER_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_CONTENT_GENRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_CONTENT_GENRE" ON "ENDITPCWK"."CONTENT_GENRE" ("CONTENT_ID", "GENRE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_CONTENT_IMAGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_CONTENT_IMAGE" ON "ENDITPCWK"."CONTENT_IMAGE" ("IMAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_CONTENT_CREDIT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_CONTENT_CREDIT" ON "ENDITPCWK"."CONTENT_CREDIT" ("CREDIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER_CONTENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_MEMBER_CONTENT" ON "ENDITPCWK"."MEMBER_CONTENT" ("MEMBER_ID", "CONTENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_PERSON_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_PERSON_LIKE" ON "ENDITPCWK"."PERSON_LIKE" ("MEMBER_ID", "PERSON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_COLLECTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_COLLECTION" ON "ENDITPCWK"."COLLECTION" ("COLLECTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_NOTICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_NOTICE" ON "ENDITPCWK"."NOTICE" ("NOTICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_COLLECTION_ITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_COLLECTION_ITEM" ON "ENDITPCWK"."COLLECTION_ITEM" ("COLLECTION_ID", "CONTENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_COLLECTION_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_COLLECTION_LIKE" ON "ENDITPCWK"."COLLECTION_LIKE" ("MEMBER_ID", "COLLECTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_USER_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_USER_COMMENT" ON "ENDITPCWK"."USER_COMMENT" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_MEMBER" ON "ENDITPCWK"."MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_GENRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_GENRE" ON "ENDITPCWK"."GENRE" ("GENRE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index UK_GENRE_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."UK_GENRE_NAME" ON "ENDITPCWK"."GENRE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index UK_GENRE_EXTERNAL_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."UK_GENRE_EXTERNAL_ID" ON "ENDITPCWK"."GENRE" ("EXTERNAL_GENRE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_CONTENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_CONTENT" ON "ENDITPCWK"."CONTENT" ("CONTENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_COMMENT_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_COMMENT_LIKE" ON "ENDITPCWK"."COMMENT_LIKE" ("MEMBER_ID", "COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_REPORT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_REPORT" ON "ENDITPCWK"."REPORT_COMMENT" ("REPORT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_COMMON_CODE_GROUP
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_COMMON_CODE_GROUP" ON "ENDITPCWK"."COMMON_CODE_GROUP" ("GROUP_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index PK_COMMON_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."PK_COMMON_CODE" ON "ENDITPCWK"."COMMON_CODE" ("CODE", "GROUP_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_MEMBER_CONTENT_CONTENT_RATING
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_MEMBER_CONTENT_CONTENT_RATING" ON "ENDITPCWK"."MEMBER_CONTENT" ("CONTENT_ID", "RATING_SCORE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_USER_COMMENT_CONTENT_CREATED
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_USER_COMMENT_CONTENT_CREATED" ON "ENDITPCWK"."USER_COMMENT" ("CONTENT_ID", "CREATED_DT" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_CONTENT_TITLE
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_CONTENT_TITLE" ON "ENDITPCWK"."CONTENT" ("TITLE_KO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index UK_MEMBER_NICKNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."UK_MEMBER_NICKNAME" ON "ENDITPCWK"."MEMBER" ("NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_MEMBER_CONTENT_RATING
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_MEMBER_CONTENT_RATING" ON "ENDITPCWK"."MEMBER_CONTENT" ("MEMBER_ID", "RATING_SCORE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_NOTICE_STATUS_IMPORTANT
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_NOTICE_STATUS_IMPORTANT" ON "ENDITPCWK"."NOTICE" ("STATUS", "IMPORTANT", "CREATED_DT" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_PERSON_NAME
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_PERSON_NAME" ON "ENDITPCWK"."PERSON" ("NAME_KO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_REPORT_STATUS_CREATED
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_REPORT_STATUS_CREATED" ON "ENDITPCWK"."REPORT_COMMENT" ("STATUS", "CREATED_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_MEMBER_SOCIAL_MEMBER
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_MEMBER_SOCIAL_MEMBER" ON "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index UK_USER_COMMENT_COLLECTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."UK_USER_COMMENT_COLLECTION" ON "ENDITPCWK"."USER_COMMENT" (CASE  WHEN "COLLECTION_ID" IS NOT NULL THEN "MEMBER_ID" END , CASE  WHEN "COLLECTION_ID" IS NOT NULL THEN "COLLECTION_ID" END ) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_MEMBER_CONTENT_WATCHLIST
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_MEMBER_CONTENT_WATCHLIST" ON "ENDITPCWK"."MEMBER_CONTENT" ("MEMBER_ID", "WATCHLIST", "WATCHLIST_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_CONTENT_GENRE_GENRE
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_CONTENT_GENRE_GENRE" ON "ENDITPCWK"."CONTENT_GENRE" ("GENRE_ID", "CONTENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_MEMBER_CREATED
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_MEMBER_CREATED" ON "ENDITPCWK"."MEMBER" ("CREATED_DT" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_COLLECTION_LIKE_COLLECTION
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_COLLECTION_LIKE_COLLECTION" ON "ENDITPCWK"."COLLECTION_LIKE" ("COLLECTION_ID", "CREATED_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_COLLECTION_TITLE
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_COLLECTION_TITLE" ON "ENDITPCWK"."COLLECTION" ("TITLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_USER_COMMENT_MEMBER
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_USER_COMMENT_MEMBER" ON "ENDITPCWK"."USER_COMMENT" ("MEMBER_ID", "CREATED_DT" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_COMMENT_LIKE_COMMENT
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_COMMENT_LIKE_COMMENT" ON "ENDITPCWK"."COMMENT_LIKE" ("COMMENT_ID", "CREATED_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_COLLECTION_MEMBER_CREATED
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_COLLECTION_MEMBER_CREATED" ON "ENDITPCWK"."COLLECTION" ("MEMBER_ID", "CREATED_DT" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_PERSON_LIKE_PERSON
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_PERSON_LIKE_PERSON" ON "ENDITPCWK"."PERSON_LIKE" ("PERSON_ID", "CREATED_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_USER_COMMENT_COLLECTION_CREATED
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_USER_COMMENT_COLLECTION_CREATED" ON "ENDITPCWK"."USER_COMMENT" ("COLLECTION_ID", "CREATED_DT" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_CONTENT_IMAGE_LIST
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_CONTENT_IMAGE_LIST" ON "ENDITPCWK"."CONTENT_IMAGE" ("CONTENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_CONTENT_CREDIT_ROLE_ORDER
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_CONTENT_CREDIT_ROLE_ORDER" ON "ENDITPCWK"."CONTENT_CREDIT" ("CONTENT_ID", "ROLE", "DISPLAY_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_CONTENT_CREDIT_PERSON
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_CONTENT_CREDIT_PERSON" ON "ENDITPCWK"."CONTENT_CREDIT" ("PERSON_ID", "CONTENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index UK_USER_COMMENT_CONTENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."UK_USER_COMMENT_CONTENT" ON "ENDITPCWK"."USER_COMMENT" (CASE  WHEN "CONTENT_ID" IS NOT NULL THEN "MEMBER_ID" END , CASE  WHEN "CONTENT_ID" IS NOT NULL THEN "CONTENT_ID" END ) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index UK_MEMBER_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENDITPCWK"."UK_MEMBER_EMAIL" ON "ENDITPCWK"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_CONTENT_COUNTRY
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_CONTENT_COUNTRY" ON "ENDITPCWK"."CONTENT" ("COUNTRY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_COLLECTION_ITEM_CONTENT
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_COLLECTION_ITEM_CONTENT" ON "ENDITPCWK"."COLLECTION_ITEM" ("CONTENT_ID", "COLLECTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_REPORT_COMMENT_TARGET
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_REPORT_COMMENT_TARGET" ON "ENDITPCWK"."REPORT_COMMENT" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  DDL for Index IDX_REPORT_REPORTER
--------------------------------------------------------

  CREATE INDEX "ENDITPCWK"."IDX_REPORT_REPORTER" ON "ENDITPCWK"."REPORT_COMMENT" ("REPORT_MEMBER_ID", "CREATED_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."MEMBER" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."MEMBER" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."MEMBER" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."MEMBER" ADD CONSTRAINT "CK_MEMBER_ROLE" CHECK (ROLE IN ('USER', 'ADMIN')) ENABLE;
  ALTER TABLE "ENDITPCWK"."MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GENRE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."GENRE" MODIFY ("EXTERNAL_GENRE_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."GENRE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY ("GENRE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
  ALTER TABLE "ENDITPCWK"."GENRE" ADD CONSTRAINT "UK_GENRE_NAME" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
  ALTER TABLE "ENDITPCWK"."GENRE" ADD CONSTRAINT "UK_GENRE_EXTERNAL_ID" UNIQUE ("EXTERNAL_GENRE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."PERSON" ADD CONSTRAINT "PK_PERSON" PRIMARY KEY ("PERSON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
  ALTER TABLE "ENDITPCWK"."PERSON" ADD CONSTRAINT "UK_PERSON_EXTERNAL" UNIQUE ("EXTERNAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
  ALTER TABLE "ENDITPCWK"."PERSON" MODIFY ("EXTERNAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."PERSON" MODIFY ("NAME_ORG" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."PERSON" MODIFY ("CREATED_DT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER_SOCIAL_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" MODIFY ("PROVIDER_CODE" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" MODIFY ("PROVIDER_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" MODIFY ("CONNECTED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" ADD CONSTRAINT "CK_MEMBER_SOCIAL_PROVIDER" CHECK (PROVIDER_CODE IN ('GOOGLE', 'KAKAO', 'NAVER')) ENABLE;
  ALTER TABLE "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" ADD CONSTRAINT "PK_MEMBER_SOCIAL_ACCOUNT" PRIMARY KEY ("MEMBER_SOCIAL_ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
  ALTER TABLE "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" ADD CONSTRAINT "UK_MEMBER_SOCIAL_PROVIDER_USER" UNIQUE ("PROVIDER_CODE", "PROVIDER_USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
  ALTER TABLE "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" ADD CONSTRAINT "UK_MEMBER_SOCIAL_MEMBER_PROVIDER" UNIQUE ("MEMBER_ID", "PROVIDER_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COLLECTION
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."COLLECTION" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COLLECTION" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COLLECTION" MODIFY ("IS_PUBLIC" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COLLECTION" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COLLECTION" ADD CONSTRAINT "CK_COLLECTION_PUBLIC" CHECK (IS_PUBLIC IN ('Y', 'N')) ENABLE;
  ALTER TABLE "ENDITPCWK"."COLLECTION" ADD CONSTRAINT "PK_COLLECTION" PRIMARY KEY ("COLLECTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMON_CODE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."COMMON_CODE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COMMON_CODE" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COMMON_CODE" MODIFY ("CODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COMMON_CODE" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COMMON_CODE" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COMMON_CODE" ADD CONSTRAINT "PK_COMMON_CODE" PRIMARY KEY ("CODE", "GROUP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTENT_IMAGE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."CONTENT_IMAGE" MODIFY ("CONTENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT_IMAGE" MODIFY ("IMAGE_URL" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT_IMAGE" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT_IMAGE" ADD CONSTRAINT "PK_CONTENT_IMAGE" PRIMARY KEY ("IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTENT_CREDIT
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."CONTENT_CREDIT" MODIFY ("CONTENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT_CREDIT" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT_CREDIT" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT_CREDIT" MODIFY ("DISPLAY_ORDER" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT_CREDIT" ADD CONSTRAINT "CK_CONTENT_CREDIT_ROLE" CHECK (ROLE IN ('ACTOR', 'DIRECTOR', 'WRITER', 'PRODUCER')) ENABLE;
  ALTER TABLE "ENDITPCWK"."CONTENT_CREDIT" ADD CONSTRAINT "CK_CONTENT_CREDIT_ORDER" CHECK (DISPLAY_ORDER >= 0) ENABLE;
  ALTER TABLE "ENDITPCWK"."CONTENT_CREDIT" ADD CONSTRAINT "PK_CONTENT_CREDIT" PRIMARY KEY ("CREDIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTENT_GENRE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."CONTENT_GENRE" MODIFY ("CONTENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT_GENRE" MODIFY ("GENRE_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT_GENRE" ADD CONSTRAINT "PK_CONTENT_GENRE" PRIMARY KEY ("CONTENT_ID", "GENRE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COLLECTION_ITEM
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."COLLECTION_ITEM" MODIFY ("ADDED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COLLECTION_ITEM" ADD CONSTRAINT "PK_COLLECTION_ITEM" PRIMARY KEY ("COLLECTION_ID", "CONTENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENT_LIKE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."COMMENT_LIKE" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COMMENT_LIKE" ADD CONSTRAINT "PK_COMMENT_LIKE" PRIMARY KEY ("MEMBER_ID", "COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMON_CODE_GROUP
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."COMMON_CODE_GROUP" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COMMON_CODE_GROUP" MODIFY ("GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COMMON_CODE_GROUP" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COMMON_CODE_GROUP" ADD CONSTRAINT "PK_COMMON_CODE_GROUP" PRIMARY KEY ("GROUP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPORT_COMMENT
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" MODIFY ("REPORT_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" MODIFY ("REASON" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" ADD CONSTRAINT "CK_REPORT_REASON" CHECK (REASON IN ('SPOILER', 'INAPPROPRIATE', 'SPAM', 'OTHER')) ENABLE;
  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" ADD CONSTRAINT "CK_REPORT_STATUS" CHECK (STATUS IN ('RECEIVED', 'PROCESSING', 'ACCEPTED', 'REJECTED')) ENABLE;
  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" ADD CONSTRAINT "CK_REPORT_OTHER_DETAIL" CHECK (REASON <> 'OTHER' OR DETAIL IS NOT NULL) ENABLE;
  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" ADD CONSTRAINT "CK_REPORT_PROCESS_COMPLETE" CHECK (
        STATUS NOT IN ('ACCEPTED', 'REJECTED') OR 
        (PROCESSED_BY_MEMBER_ID IS NOT NULL AND PROCESSED_DT IS NOT NULL)
    ) ENABLE;
  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY ("REPORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER_CONTENT
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."MEMBER_CONTENT" MODIFY ("WATCHLIST" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."MEMBER_CONTENT" MODIFY ("UPDATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."MEMBER_CONTENT" ADD CONSTRAINT "CK_MEMBER_CONTENT_RATING" CHECK (RATING_SCORE IS NULL OR RATING_SCORE BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "ENDITPCWK"."MEMBER_CONTENT" ADD CONSTRAINT "CK_MEMBER_CONTENT_WATCHLIST" CHECK (WATCHLIST IN ('Y', 'N')) ENABLE;
  ALTER TABLE "ENDITPCWK"."MEMBER_CONTENT" ADD CONSTRAINT "CK_MEMBER_CONTENT_NOT_EMPTY" CHECK (RATING_SCORE IS NOT NULL OR WATCHLIST = 'Y') ENABLE;
  ALTER TABLE "ENDITPCWK"."MEMBER_CONTENT" ADD CONSTRAINT "PK_MEMBER_CONTENT" PRIMARY KEY ("MEMBER_ID", "CONTENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."NOTICE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."NOTICE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."NOTICE" MODIFY ("IMPORTANT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."NOTICE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."NOTICE" MODIFY ("VIEW_COUNT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."NOTICE" MODIFY ("CREATED_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."NOTICE" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."NOTICE" MODIFY ("UPDATED_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."NOTICE" ADD CONSTRAINT "CK_NOTICE_IMPORTANT" CHECK (IMPORTANT IN ('Y', 'N')) ENABLE;
  ALTER TABLE "ENDITPCWK"."NOTICE" ADD CONSTRAINT "CK_NOTICE_STATUS" CHECK (STATUS IN ('DRAFT', 'PUBLISHED', 'HIDDEN')) ENABLE;
  ALTER TABLE "ENDITPCWK"."NOTICE" ADD CONSTRAINT "CK_NOTICE_VIEW_COUNT" CHECK (VIEW_COUNT >= 0) ENABLE;
  ALTER TABLE "ENDITPCWK"."NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY ("NOTICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_COMMENT
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."USER_COMMENT" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."USER_COMMENT" MODIFY ("COMMENT_DETAIL" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."USER_COMMENT" MODIFY ("SPOILER" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."USER_COMMENT" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."USER_COMMENT" ADD CONSTRAINT "CK_USER_COMMENT_TARGET_ONE" CHECK (
        (CONTENT_ID IS NOT NULL AND COLLECTION_ID IS NULL) OR 
        (CONTENT_ID IS NULL AND COLLECTION_ID IS NOT NULL)
    ) ENABLE;
  ALTER TABLE "ENDITPCWK"."USER_COMMENT" ADD CONSTRAINT "CK_USER_COMMENT_SPOILER" CHECK (SPOILER IN ('Y', 'N')) ENABLE;
  ALTER TABLE "ENDITPCWK"."USER_COMMENT" ADD CONSTRAINT "PK_USER_COMMENT" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COLLECTION_LIKE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."COLLECTION_LIKE" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."COLLECTION_LIKE" ADD CONSTRAINT "PK_COLLECTION_LIKE" PRIMARY KEY ("MEMBER_ID", "COLLECTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSON_LIKE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."PERSON_LIKE" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."PERSON_LIKE" ADD CONSTRAINT "PK_PERSON_LIKE" PRIMARY KEY ("MEMBER_ID", "PERSON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTENT
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."CONTENT" MODIFY ("EXTERNAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT" MODIFY ("TITLE_ORG" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "ENDITPCWK"."CONTENT" ADD CONSTRAINT "PK_CONTENT" PRIMARY KEY ("CONTENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ENDIT_WEB_TS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COLLECTION
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."COLLECTION" ADD CONSTRAINT "FK_COLLECTION_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "ENDITPCWK"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COLLECTION_ITEM
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."COLLECTION_ITEM" ADD CONSTRAINT "FK_COLLECTION_ITEM_COLLECTION" FOREIGN KEY ("COLLECTION_ID")
	  REFERENCES "ENDITPCWK"."COLLECTION" ("COLLECTION_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."COLLECTION_ITEM" ADD CONSTRAINT "FK_COLLECTION_ITEM_CONTENT" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES "ENDITPCWK"."CONTENT" ("CONTENT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COLLECTION_LIKE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."COLLECTION_LIKE" ADD CONSTRAINT "FK_COLLECTION_LIKE_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "ENDITPCWK"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."COLLECTION_LIKE" ADD CONSTRAINT "FK_COLLECTION_LIKE_COLLECTION" FOREIGN KEY ("COLLECTION_ID")
	  REFERENCES "ENDITPCWK"."COLLECTION" ("COLLECTION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENT_LIKE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."COMMENT_LIKE" ADD CONSTRAINT "FK_COMMENT_LIKE_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "ENDITPCWK"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."COMMENT_LIKE" ADD CONSTRAINT "FK_COMMENT_LIKE_COMMENT" FOREIGN KEY ("COMMENT_ID")
	  REFERENCES "ENDITPCWK"."USER_COMMENT" ("COMMENT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMON_CODE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."COMMON_CODE" ADD CONSTRAINT "FK_CODE_GROUP" FOREIGN KEY ("GROUP_CODE")
	  REFERENCES "ENDITPCWK"."COMMON_CODE_GROUP" ("GROUP_CODE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTENT_CREDIT
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."CONTENT_CREDIT" ADD CONSTRAINT "FK_CONTENT_CREDIT_CONTENT" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES "ENDITPCWK"."CONTENT" ("CONTENT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."CONTENT_CREDIT" ADD CONSTRAINT "FK_CONTENT_CREDIT_PERSON" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "ENDITPCWK"."PERSON" ("PERSON_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTENT_GENRE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."CONTENT_GENRE" ADD CONSTRAINT "FK_CONTENT_GENRE_CONTENT" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES "ENDITPCWK"."CONTENT" ("CONTENT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."CONTENT_GENRE" ADD CONSTRAINT "FK_CONTENT_GENRE_GENRE" FOREIGN KEY ("GENRE_ID")
	  REFERENCES "ENDITPCWK"."GENRE" ("GENRE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTENT_IMAGE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."CONTENT_IMAGE" ADD CONSTRAINT "FK_CONTENT_IMAGE_CONTENT" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES "ENDITPCWK"."CONTENT" ("CONTENT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER_CONTENT
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."MEMBER_CONTENT" ADD CONSTRAINT "FK_MEMBER_CONTENT_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "ENDITPCWK"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."MEMBER_CONTENT" ADD CONSTRAINT "FK_MEMBER_CONTENT_CONTENT" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES "ENDITPCWK"."CONTENT" ("CONTENT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER_SOCIAL_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."MEMBER_SOCIAL_ACCOUNT" ADD CONSTRAINT "FK_MEMBER_SOCIAL_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "ENDITPCWK"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."NOTICE" ADD CONSTRAINT "FK_NOTICE_CREATED_ADMIN" FOREIGN KEY ("CREATED_ID")
	  REFERENCES "ENDITPCWK"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."NOTICE" ADD CONSTRAINT "FK_NOTICE_UPDATED_ADMIN" FOREIGN KEY ("UPDATED_ID")
	  REFERENCES "ENDITPCWK"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSON_LIKE
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."PERSON_LIKE" ADD CONSTRAINT "FK_PERSON_LIKE_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "ENDITPCWK"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."PERSON_LIKE" ADD CONSTRAINT "FK_PERSON_LIKE_PERSON" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "ENDITPCWK"."PERSON" ("PERSON_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORT_COMMENT
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" ADD CONSTRAINT "FK_REPORT_REPORTER" FOREIGN KEY ("REPORT_MEMBER_ID")
	  REFERENCES "ENDITPCWK"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" ADD CONSTRAINT "FK_REPORT_COMMENT" FOREIGN KEY ("COMMENT_ID")
	  REFERENCES "ENDITPCWK"."USER_COMMENT" ("COMMENT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."REPORT_COMMENT" ADD CONSTRAINT "FK_REPORT_ADMIN" FOREIGN KEY ("PROCESSED_BY_MEMBER_ID")
	  REFERENCES "ENDITPCWK"."MEMBER" ("MEMBER_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_COMMENT
--------------------------------------------------------

  ALTER TABLE "ENDITPCWK"."USER_COMMENT" ADD CONSTRAINT "FK_USER_COMMENT_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "ENDITPCWK"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."USER_COMMENT" ADD CONSTRAINT "FK_USER_COMMENT_CONTENT" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES "ENDITPCWK"."CONTENT" ("CONTENT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ENDITPCWK"."USER_COMMENT" ADD CONSTRAINT "FK_USER_COMMENT_COLLECTION" FOREIGN KEY ("COLLECTION_ID")
	  REFERENCES "ENDITPCWK"."COLLECTION" ("COLLECTION_ID") ON DELETE CASCADE ENABLE;
