# 서버 포트 설정
server.port=8080

# Oracle DB 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=endit_test
spring.datasource.password=qwer1234

# MyBatis 설정
# type-alias에서 클래스명 충돌 발생 시(ex. CommentVO) → @Alias("UserCommentVO")처럼 별칭을 직접 지정 
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.endit



# Thymeleaf 캐시 비활성화 (개발 중 프론트 수정 반영용)
spring.thymeleaf.cache=false
